name: Playwright Tests for Saily

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: html-report
          path: reports/html-report/

      - name: Upload test results (screenshots, videos, traces)
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-results
          path: test-results/

      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: junit-report
          path: reports/junit-report.xml
